version: '3.4'
services:
  generator:
    image: mozmeao/generate-sitemap:latest
    env_file:
      - .bedrock.env
    build:
      context: .
    command: ./run-generator.sh
    volumes:
      - ./data:/app/sitemap-data:delegated
